repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Simply check whether files parse as valid python.
      - id: check-ast
      # Attempts to load all json files to verify syntax.
      - id: check-json
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Attempts to load all yaml files to verify syntax.
      - id: check-yaml
        args: [ "--unsafe" ]
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
        exclude: tests/
      # Trims trailing whitespace.
      - id: trailing-whitespace
        exclude: tests/
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Check for debugger imports and py37+ breakpoint() calls.
      - id: debug-statements
        exclude: tests/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff-format
        args: [ "--config", "$RUFF_CONFIG_PATH" ]
        exclude: migrations/
